create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  company_name text not null,
  phone text not null,
  subject text not null,
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;

create policy "allow public inquiry inserts"
on public.inquiries
for insert
to anon
with check (true);

create index if not exists inquiries_created_at_idx
on public.inquiries (created_at desc);
