create table if not exists public.products (
  id bigint generated by default as identity primary key,
  manufacturer text not null,
  name text not null,
  category text not null default '산업용 페인트',
  usage text,
  specification text,
  stock_status text not null default '문의',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

create policy "allow public product reads"
on public.products
for select
to anon, authenticated
using (is_active = true or auth.role() = 'authenticated');

create policy "allow authenticated product writes"
on public.products
for all
to authenticated
using (true)
with check (true);

create index if not exists products_manufacturer_idx on public.products (manufacturer);
create index if not exists products_name_idx on public.products (name);
