create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  manufacturer text not null,
  title text not null,
  resource_type text not null default '카탈로그',
  file_url text not null,
  description text,
  created_at timestamptz not null default now()
);

alter table public.resources enable row level security;

create policy "allow public resource reads"
on public.resources
for select
to anon, authenticated
using (true);

create policy "allow authenticated resource inserts"
on public.resources
for insert
to authenticated
with check (true);

create policy "allow authenticated resource updates"
on public.resources
for update
to authenticated
using (true)
with check (true);

create policy "allow authenticated resource deletes"
on public.resources
for delete
to authenticated
using (true);

create index if not exists resources_created_at_idx
on public.resources (created_at desc);

create index if not exists resources_manufacturer_idx
on public.resources (manufacturer);
